[font]
size = 15.0

[font.offset]
x = 0
y = 2  # Increase this integer to add line spacing (e.g., 2, 3, or 4)

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[window]
padding = { x = 12, y = 12 }
opacity = 0.75
blur = true

[colors.primary]
background = "#000000"
foreground = "#E0E0E0"

[colors.cursor]
cursor = "#FFFFFF"
text = "#000000"

[colors.selection]
background = "#FFFFFF"
text = "#000000"

# Normal Colors
[colors.normal]
black   = "#000000"
red     = "#800000"
green   = "#008000"
yellow  = "#808000"
blue    = "#000080"
magenta = "#800080"
cyan    = "#008080"
white   = "#C0C0C0"

# Bright Colors
[colors.bright]
black   = "#808080"
red     = "#FF0000"
green   = "#00FF00"
yellow  = "#FFFF00"
blue    = "#0000FF"
magenta = "#FF00FF"
cyan    = "#00FFFF"
white   = "#FFFFFF"

[[keyboard.bindings]]
key = "F11"
mods = "None"
action = "ToggleFullscreen"

[colors]
draw_bold_text_with_bright_colors = true
