[main]
font=Monospace:size=11
prompt="❯ "
icon-theme=hicolor
fields=filename,name,generic,exec,keywords
terminal=alacritty -e
lines=20
width=60
horizontal-pad=20
vertical-pad=12
inner-pad=8
image-size-ratio=0.5

[border]
width=2
radius=8

[colors]
# Format: RRGGBBAA (Hex with Alpha)
background=0d0204e6
text=ffffffff
prompt=ff1744ff
placeholder=66222eff
input=ffffffff
match=ff1744ff
selection=4a0d18ff
selection-text=ff5252ff
selection-match=ffffffff
border=ff1744ff
