[main]
font=Hack Nerd Font Mono:size=11
prompt="WIRED❯ "
icon-theme=hicolor
fields=filename,name,generic,exec,keywords
terminal=alacritty -e
lines=20
width=60
horizontal-pad=20
vertical-pad=12
inner-pad=8
image-size-ratio=0.5

[border]
width=2
radius=10

[colors]
# Format: RRGGBBAA
background=0b0a12e6
text=e2d9f3ff
prompt=bf94ffff
placeholder=635380ff
input=ffffffff
match=ff79c6ff
selection=3b2d54e6
selection-text=ffffffff
selection-match=f1fa8cff
border=bf94ffff
