background {
    monitor =
    path = /home/ext/Pictures/Wallpapers/wallpaperswide.com-abstract-distorted-strings-wallpaper-1920x1080.jpg   # Or screenshot
    blur_passes = 3
    blur_size = 8
}

general {
    ignore_empty_input = true
    grace = 0
}

# Time Widget
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 64
    font_family = Hack Nerd Font Mono
    position = 0, 80
    halign = center
    valign = center
}

# Date Widget
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(136, 192, 208, 1.0)
    font_size = 18
    font_family = Hack Nerd Font Mono
    position = 0, 10
    halign = center
    valign = center
}

# Password Field
input-field {
    monitor =
    size = 220, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    fade_on_empty = false
    font_color = rgb(255, 255, 255)
    inner_color = rgba(0, 0, 0, 0.5)
    outer_color = rgb(136, 192, 208)
    position = 0, -80
    halign = center
    valign = center
}
