[main]
font=Monospace:size=11
prompt="❯ "
icon-theme=hicolor
fields=filename,name,generic,exec,keywords
terminal=alacritty -e
lines=20
width=60
horizontal-pad=20
vertical-pad=12
inner-pad=8
image-size-ratio=0.5

[border]
width=2
radius=8

[colors]
# Format: RRGGBBAA (Hex with Alpha)
background=050a06d9
text=ffffffff
prompt=00ff66ff
placeholder=2d5e38ff
input=ffffffff
match=00ff66ff
selection=0f381bff
selection-text=00ff66ff
selection-match=ffffffff
border=00ff66ff
